# Generated by Django 5.1.1 on 2024-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_rename_logo_url_team_espn_logo_url_team_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
