# Generated by Django 5.1.1 on 2024-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_remove_pick_league_remove_pick_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bye_week',
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
