# Generated by Django 5.1.1 on 2024-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_remove_team_bye_week_team_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='logo_url',
            new_name='espn_logo_url',
        ),
        migrations.AddField(
            model_name='team',
            name='color_1',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color_2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color_3',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color_4',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='squared_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wikipedia_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wordmark_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
